### ISSUE TITLE
Yesod Integration

### ISSUE THREAD

**Issue by lippling** [tomjaguarpaw/haskell-opaleye#11]
Can someone give me hints how to replace Persistent with OpalEye in a scaffolded Yesod 1.4 application?

**Comment by lippling** [comment]
Any news here?

**Comment by tomjaguarpaw** [comment]
I'm afraid not.  Unless someone who knows Persistent and/or Yesod can help out we'll remain stuck.

**Comment by richardfergie** [comment]
It would be possible to use OpalEye instead of Persistent but you'd lose a lot of the nice templating that Persistent provides when used with the Yesod scaffolding.

The simplest thing to do would be to just thread OpalEye through manually but this seems quite inelegant and I'm not sure how it would work with things like Authorization. I use Persistent for the kind of "core web framework" stuff and then OpalEye for the domain specific stuff. i.e. "get the user who is currently logged in" runs through persistent but "get all the widgets that the user ordered but which have not yet been shipped" runs through OpalEye.

You *might* be able to place OpalEye code in the definitions of the typeclasses in [Yesod.Persist.Core](https://hackage.haskell.org/package/yesod-persistent-1.4.0.3/docs/Yesod-Persist-Core.html) but I'm not sure how difficult this would be. I believe the purpose of these typeclasses is to abstract away the database implementation from the app, but they seem pretty wedded to Persistent in practice

**Comment by lippling** [comment]
Hi @richardfergie,

thanks for your reply.
I thought about the same: CRUD -> Persistent and specialized queries -> Opaleye.

How do you deal with connection pooling and Opaleye?

**Comment by richardfergie** [comment]
I make a separate pool of connections for Opaleye and store this in Yesod's foundation data type.

[Data.Pool](https://hackage.haskell.org/package/resource-pool-0.2.3.2/docs/Data-Pool.html) makes this pretty easy. Just create the pool in Application.hs and then you can access it using `getYesod` when you need to.

I think everything uses [Database.PostgreSQL.LibPQ](https://hackage.haskell.org/package/postgresql-libpq-0.9.1.1/docs/Database-PostgreSQL-LibPQ.html) under the hood so Opaleye and Persistent should be able to pull from the same pool but I can't figure out how to make it work.

**Comment by lippling** [comment]
Ok thanks!
I'll give it a try, when I have time in the next weeks or so.

**Comment by tomjaguarpaw** [comment]
I'm closing this because it's very old and I don't have any concrete plans to address it. If you think it still needs addressing or have any further details to add then please reopen or file a new issue.
