### ISSUE TITLE
Using opaleye to query pure Haskell data

### ISSUE THREAD

**Issue by abailly** [tomjaguarpaw/haskell-opaleye#127]
Hello,
I have a use case where I want to be able to query data in pure Haskell records/lists. Obviously, this can be done easily using Haskell code... The point is that I want to have an external representation for those queries so that, e.g. we can define them once and provide different interpretations. What I am looking for is something like LINQ which allow expressing queries declaratively without taking care of the data source, and in my case and want to run such queries against in-memory data. 

Would it be possible/interesting/convenient to do that with opaleye? Can I provide a specialized interpreter for queries represented in opaleye's model?

**Comment by tomjaguarpaw** [comment]
This is a very cool idea in general, and something that would be useful to have in Haskell. I would encourage you to try. It involves adding some of the querying functionality of relational databases into Haskell, because to be efficient the query would have to be run using indices on the data, or perhaps something like "discrimination" the Ed Kmett's been working on.  You can certainly use the internal `PrimQuery` of Opaleye (or something very much like it) to represent these queries.

**Comment by abailly** [comment]
Thanks. To make my question more precise: where should I start in opaleye's codebase to try to write couple of queries and see where it goes?

**Comment by tomjaguarpaw** [comment]
An Opaleye `Query` is essentially a [`PrimQuery`](https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Internal/PrimQuery.hs).  This is an AST of relational operations with concrete tables at the leaves.  Some of the operations also refer to columns of the tables.

What you essentially need to do is write an in-Haskell handler for `PrimQuery`.  If you intended to interpret the `PrimQuery` in Haskell list type, for example, you could interpret `Unit` as `[()]`, `Product` as `liftA2 (,)`, `Order` as a `sortBy` operation, `Limit` as a `take`, etc., etc..

**Comment by tomjaguarpaw** [comment]
This seems expired.  Feel free to reopen or file a new issue if not.
