### ISSUE TITLE
How to do a runInsertManyReturning?

### ISSUE THREAD

**Issue by tusj** [tomjaguarpaw/haskell-opaleye#131]
I am getting started with Opaleye and find myself wanting to do a `runInsertManyReturning` as I want to insert many values at once, returning an id for each row inserted. In Opaleye, we can only either do `runInsertReturning` or `runInsertMany`.

I only see this functionality in the "opaleye-trans" package: [insertManyReturning](https://hackage.haskell.org/package/opaleye-trans-0.2.0/docs/Opaleye-Trans.html#v:insertManyReturning) where the documentation lists it as:
>Maybe not worth defining. This almost certainly does the wrong thing.

Is there a reason I cannot do this with Opaleye? Is it considered bad practice?

For the record, I have limited experience with Sql.
What I want to do is a:
`INSERT INTO dbname VALUES (_, _,_), (_, _, _) RETURNING id;`

**Comment by tomjaguarpaw** [comment]
This sounds like a valid thing to want, and the only reason it doesn't exist is that no one has requested it yet!  If you want to have a go at adding this yourself, you can try adapting [`arrangeInsertReturning`](https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Manipulation.hs#L177) to use `arrangeInsertMany` internally, rather than `arrangeInsert`.  Otherwise, I'll add it to my TODO list.

opaleye-trans's `insertManyReturning` just runs `insertReturning` multiple times, and this is probably not what you want.

**Comment by tusj** [comment]
I will see what I can do. It should be a simple thing to do, but I have to familiarize myself more with the opaleye internals. Yes, I checked the implementation for opaleye-trans, and that was the implementation I specifically wanted to avoid. Functionally correct, but inefficient!

**Comment by tusj** [comment]
I have made a rudimentray fix. However, there is a question of API: To do a `runInsert` you can simply wrap the value to be inserted and just use `runInsertMultiple`. This is the case for both `runInsert` and `runInsertReturning`.  In the fix I have rewritten `runInsertReturning` to accept a list as argument, complying with the previous thought, but I have left `runInsert` and `runInsertMultiple` as before.

**Comment by tomjaguarpaw** [comment]
Hi there, happy to merge your fix and close the issue when you squash the commits into one.  Thanks.

**Comment by tusj** [comment]
Thanks for the reminder, got a little hectic around Christmas time. I will fix it.

**Comment by tomjaguarpaw** [comment]
`runInsertManyReturning` has already been added https://github.com/tomjaguarpaw/haskell-opaleye/pull/132
