### ISSUE TITLE
Window functions

### ISSUE THREAD

**Issue by boothead** [tomjaguarpaw/haskell-opaleye#149]
Hi,

Any plans to be able to use window functions in querying with opaleye (or can you already)?

http://www.postgresql.org/docs/9.5/static/functions-window.html

**Comment by tomjaguarpaw** [comment]
Hello, window functions are not implemented yet and I have not particular plans to add them but I'm happy to assist or collaborate.

**Comment by boothead** [comment]
To be honest, I have no particular idea what that might look like. If I start thinking about it a bit more seriously I may start peppering you with questions :-)

**Comment by tomjaguarpaw** [comment]
I've never used window functions so I couldn't say what they would look like but if you start to seriously need them then give me a shout.

**Comment by xnmp** [comment]
@tomjaguarpaw 

The main reason I want a window function is the following situation: say there's a table of people, together with a date that they got married, and a list of the meals that each of those people had every day. I want to know the last meal each person had before they got married. 

This situation arises pretty commonly, and the only way I can do it now is to left join twice, which of course is pretty unwieldy in Opaleye. If I had window functions, I could write

```sql
SELECT * from 
(select *, row_num over (partition by person order by meal_date desc)
from meals, persons 
where meals.person = persons.person and meals.meal_date < person.married_date)
where rownum = 1
```

without it has to be

```sql
select * from meals
left join meals on meals.person1 = person.person and meals1.date < person.married_date
left join meals2 on meals2.person = meals1 .person and meals2.meal_date < meals1.meal_date
where meals2.person is null
```

I tried doing this as a workaround:

```haskell
rownum :: Column a → Column b → Column Int
rownum cola colb = over (parti cola `space` ordpart colb)
  where
    over (O.Column a) = O.Column (HPQ.FunExpr "row_number() over" [a])
    parti (O.Column a) = O.Column (HPQ.FunExpr "partition by" [a])
    ordpart (O.Column a) = O.Column (HPQ.FunExpr "order by" [a])
    space = O.binOp $ HPQ.OpOther "xxx"
```

And then just modify the queryat the end to replace all instances of ```(aaa) xxx (bbb)``` with ```aaa bbb```. 
Problem is that when I do something later with the row number, it tries to put the row number in the "where" clause, which isn't allowed, rather than using it in a subquery. Is there a way to force it into a subquery?
