### ISSUE TITLE
Count query broke from 0.3 to 0.4.

### ISSUE THREAD

**Issue by dbp** [tomjaguarpaw/haskell-opaleye#159]
I just finally upgraded a site that was using opaleye 0.3 to 0.4 (I was not doing it because of the breaking semantic change on updates in #92), and was (unhappily) surprised that some select queries had also broken.

I have a pretty straightforward query that selects from a table, restricts by a few things, and then aggregates count over it. 

The code looks like:

```
q :: T -> Query (Column PGInt8)
q t = aggregate (p1 count)
  ((proc () -> do (i, tid, iid, ...) <- queryTable tTable -< ()
                  restrict -< tid .== pgInt4 (tId t)
                  restrict -< isNull iid
                  returnA -< i) :: Query (Column PGInt4))
```

With 0.3, this generated a query like:

```
SELECT "result0_2" as result1_3
FROM (SELECT *
      FROM (SELECT COUNT("id0_1") as result0_2
            FROM (SELECT *
                  FROM (SELECT "id" as id0_1,
                                              ...
                        FROM table as T1) as T1
                  WHERE ("somecol3_1" IS NULL) AND (("othercol1_1") = 315)) as T1) as T1) as T1
```

Which correctly returned the count, even in the case that there were no rows (in which case the count was zero). 

When I switched to 0.4, this query suddenly started generating:

```
SELECT "result0_2" as "result1_3"
FROM (SELECT *
      FROM (SELECT COUNT("id0_1") as "result0_2"
            FROM (SELECT *
                  FROM (SELECT "id" as "id0_1",
                               ...
                        FROM "table" as "T1") as "T1"
                  WHERE ("somecol3_1" IS NULL) AND (("othercol1_1") = 315)) as "T1"
            GROUP BY COALESCE(0)) as "T1") as "T1"
```

I'm not actually sure what `GROUP BY COALESCE(0)` does, but this query is now returning _no_ rows when there are no matches and only returning the count if there are rows. This broke things at runtime, because, expecting to get a count, I took the head of the result.

Is this expected? Can it be fixed? I didn't see any reference to changes in the semantics of `count` in the CHANGELOG, or I would have been on the lookout for this!

**Comment by tomjaguarpaw** [comment]
Hi Daniel, thanks for the report.

Firstly, I'm sorry there was a change in behaviour without warning.  I didn't think through the full consequences of the change and empty aggregations are not tested in the test suite https://github.com/tomjaguarpaw/haskell-opaleye/issues/160

The current behaviour is indeed intentional, and I think sensible, though I realise that is up for debate.  Postgres behaviour (perhaps mandated by the SQL standard?) is to return a singleton `0` on a count of an empty query.  This behaviour is inconsistent.  Consistent behaviour would imply that empty groups do not appear in the output of an aggregation.  An empty query has *only* empty groups (whichever way you group it) thus the output of any aggregation of an empty query should be empty.

The argument against this behaviour would say "despite inconsistency, we should try to not differ from Postgres behaviour for similar-looking queries".  I don't really like that argument.  I'd prefer to provide an implementation that satisfies more sensible laws than SQL itself.

The **important question**: Do you somehow rely on the old behaviour?  Is changing `head` to `headDef 0` sufficient for you, or are there reasons you can't do that?  Of course it would have been preferable to receive warning about this, but because that ship has sailed I am now primarily concerned with ensuring your client code can continue to work.

**Comment by dbp** [comment]
Hey Tom,

So... First, to your last point - no, it's quite easy to fix (and I already have!), but... I think it is going to be counter-intuitive to anyone using Opaleye, and will be something that I will need to tell people that I'm training. Obeying internal consistent laws is great, but if those laws aren't apparent (and not consistent with SQL, which is the primary frame of reference for someone using Opaleye), I'm not sure how much benefit they have.

And I guess the reason why it seems counter-intuitive to me is that this means that counting, with opaleye, will never return 0? From the perspective of a library user, I can't actually imagine a place where I wouldn't want to get 0 if I'm counting (but, I might not be thinking about the way that these compose properly!).

Perhaps the real problem is that aggregations and counting rows are slightly different (ie, aggregations need to compose; counting rows does not!). Could opaleye provide a non-composable `countRows` primitive (which could either return SQL, or actually use a connection and return the actual number)? That might actually resolve both of my issues - as it would provide an obvious way to do this (obvious in that it would be readily apparent from library documentation!)

**Comment by tomjaguarpaw** [comment]
> this means that counting, with opaleye, will never return 0? From the perspective of a library user, I can't actually imagine a place where I wouldn't want to get 0 if I'm counting

Correct, and I agree it's not particularly *useful* behaviour.  However, SQL is a particularly poorly designed language and Opaleye's aim is to mitigate its poor design rather than preserve it.

A `countRows` primitive sounds like a fine compromise, though I don't have the time to work on such a thing right now.

**Comment by tomjaguarpaw** [comment]
See also https://github.com/tomjaguarpaw/haskell-opaleye/issues/138#issuecomment-172246129

**Comment by tomjaguarpaw** [comment]
`countRows` now exists.  If you have any related issues please open a new ticket.

https://github.com/tomjaguarpaw/haskell-opaleye/commit/5aab5dcc0198c231ec46b62d55249097dc9490ee

**Comment by dbp** [comment]
Thanks @tomjaguarpaw !

**Comment by tomjaguarpaw** [comment]
You're welcome.
