### ISSUE TITLE
CaseSqlExpr should be a Maybe non-empty list

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#184]
CaseSqlExpr should be a Maybe non-empty list to make the code in Erik's patch slightly nicer:

https://github.com/tomjaguarpaw/haskell-opaleye/pull/183

**Comment by tomjaguarpaw** [comment]
@hesselink This might be something you want to tackle.  If not, no problem, I'll do it when I get round to it.

**Comment by tomjaguarpaw** [comment]
| CaseSqlExpr [(SqlExpr,SqlExpr)] SqlExpr

could be

    | CaseSqlExpr (Maybe (NEL.NonEmpty (SqlExpr,SqlExpr))) SqlExpr

An alternative would be

    | CaseSqlExpr (NEL.NonEmpty (SqlExpr,SqlExpr)) SqlExpr

and we transform empty cases to their default when we convert `PrimQuery` to SQL.

**Comment by hesselink** [comment]
I actually started this way, but it makes the code a lot more involved at no real benefit. The way I ended up thinking about it: there's a pretty sensible semantics for an empty list of case alternatives, just like in Haskell `any` and `all` are perfectly well defined on empty lists. So just solving this in code generation seemed like the right solution to me. What would be the advantage to the representation change that you see?

**Comment by tomjaguarpaw** [comment]
That's interesting.  In what way did you find the code more involved?

The advantage that I see is that `CaseSqlExpr` would communicate more accurately: it would *always* represent an SQL case statement, rather than sometimes being an SQL case statement and sometimes being a simple expression.

I would welcome your input on this.

**Comment by hesselink** [comment]
It was just that there were many more changes: instead of making the choice during SQL generation, the choice was made in `(unsafe)case_`. Then two data types needed to be changed, changing some uses of them as well. It wasn't horrible or anything, but the PR I sent was a much smaller change.

I do see your point of mapping `CaseSqlExpr` directly to a case expression. However, it would still mean that `case_` doesn't map directly to a case expression, and that is what the user will call, so I don't know how much that adds. Perhaps we could say that this is a(nother) wart in SQL: that it doesn't allow case statements without a single `when`, and opaleye fixes that :)

**Comment by tomjaguarpaw** [comment]
I agree that `(unsafe)case_` should map to a `CaseExpr` containing a list, but I think that when converting to a `CaseSqlExpr` at https://github.com/tomjaguarpaw/haskell-opaleye/blob/965c3e0c0083792b2f609febd905c8e14e3fd97a/src/Opaleye/Internal/HaskellDB/Sql/Default.hs#L131 that we should convert to either a `NonEmpty SqlExr` or `SqlExpr`.

**Comment by tomjaguarpaw** [comment]
That way *Opaleye's* case type does the right thing: case alternatives can be empty, but also the SQL representation does the right thing: case alternatives cannot be empty.

**Comment by tomjaguarpaw** [comment]
@hesselink What do you think? https://github.com/tomjaguarpaw/haskell-opaleye/pull/185

**Comment by tomjaguarpaw** [comment]
Direct link to changes: https://github.com/tomjaguarpaw/haskell-opaleye/pull/185/files

**Comment by hesselink** [comment]
That looks fine to me!
