### ISSUE TITLE
Leaking into GROUP BY

### ISSUE THREAD

**Issue by llelf** [tomjaguarpaw/haskell-opaleye#19]
Not a bug per se, but is there anything can be done about it?

```haskell
{-# LANGUAGE Arrows #-}
import Opaleye
import qualified Database.PostgreSQL.Simple as PGS
import Control.Arrow

q2 :: Column PGInt4 -> Query (Column PGInt4)
q2 i = proc () -> do
          -- x <- queryTable tableX -< ()  -- one column for simplicity
          -- restrict -< x .== i
          returnA -< i

a2 :: Column PGInt4 -> Query (Column PGInt4)
a2 i = (aggregate groupBy) (q2 i)

main = do
  c <- PGS.connect connectInfo
  r <- runQuery c (a2 1) :: IO [Int]  -- it will “GROUP BY (1)” [sic]
  print r

connectInfo :: PGS.ConnectInfo
```

**Comment by tomjaguarpaw** [comment]
What behaviour were you expecting?

This is in fact a bug, because Postgres (and I suppose SQL in general) interprets `GROUP BY` of a literal integer as grouping by the output column in that ordinal position.  See [the Postgres manual](http://www.postgresql.org/docs/9.4/static/sql-select.html#SQL-GROUPBY).

It's not clear what the best way to solve this is.  One work-around would be to `+ 0` onto integer literals when they have a chance of appearing in a `GROUP BY`.

**Comment by tomjaguarpaw** [comment]
This should now be fixed.  Can you confirm?

**Comment by tomjaguarpaw** [comment]
Confirmed fixed.  This

    {-# LANGUAGE Arrows #-}
    import Opaleye
    import Control.Arrow
    
    q2 :: Column PGInt4 -> Query (Column PGInt4)
    q2 i = proc () -> do
              -- x <- queryTable tableX -< ()  -- one column for simplicity
              -- restrict -< x .== i
              returnA -< i
    
    a2 :: Column PGInt4 -> Query (Column PGInt4)
    a2 i = (aggregate groupBy) (q2 i)
    
    main :: IO ()
    main = putStrLn (showSqlForPostgres (a2 1))

produces this

    SELECT "result0_1" as "result1_2"
    FROM (SELECT *
          FROM (SELECT 1 as "result0_1"
                FROM (SELECT 0) as "T1"
                GROUP BY COALESCE(1)) as "T1") as "T1"
