### ISSUE TITLE
Reducing boilerplate

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#200]
Referring to https://github.com/nomicflux/servant-opaleye-blog/blob/lesson2_opaleye/README.md . Questions:

Do most Opaleye apps require FOUR data-types for any entity? AppRead, AppWrite, PGRead,. PGWrite? If yes, is there any plan to avoid this boilerplate code for cases where no special behaviour is required? Are there any plans to adopt "convention over configuration" (column names map to record field names predictably, PG types map to Haskell types predictably)

If there are any invariants that need to be ensured irrespective of where user input is coming from (ie the invariant needn't be part of user-input validation), what is the appropriate place to put such code? The `appToPg` conversion function?

**Comment by bergmark** [comment]
Overall every "convention over configuration" that opaleye enforces is a potential deal breaker for a user. It's one of the reasons we couldn't use persistent. I think these things belong in external libraries, although opaleye could contain fully configurable helpers for some of this.

> Do most Opaleye apps require FOUR data-types for any entity?
As with the examples we have one fully polymorphic type at the bottom, but we only have two type aliases (one for the haskell side and one for the sql side) and then a type family on top of that which let's us say things like `To Column User = User (Column a) (Column b)`. This is all we need for 90% of queries. For the rest, such as aggregations, we can resort to tuples or writing out the full type signature. Maybe OverloadedRecordFields can make this even cleaner?

> PG types map to Haskell types predictably
Here we chose to have a one-to-many mapping (one PG type maps to several haskell types). This is probably also too (or not enough) restrictive for some. I would like a way to work around all the ambiguity opaleye's many-to-many mapping results in because this still affects us. Maybe it's possible, I haven't really thought about it.

In the end the code we write looks quite different from "standard" opaleye but it lets us go down a level of abstraction if we need something outside of our conventions. It might be interesting for you to `--ddump-splices` on our example https://github.com/silkapp/silk-opaleye/blob/master/example/User.hs

**Comment by saurabhnanda** [comment]
> Overall every "convention over configuration" that opaleye enforces is a potential deal breaker for a user. It's one of the reasons we couldn't use persistent. I think these things belong in external libraries, although opaleye could contain fully configurable helpers for some of this.

I'm not suggesting that we hardwire the conventions. In suggesting sensible defaults that word out-of-the-box with minimal configuration. The user should always have the ability to override all defaults and tweak every setting to heart'a content (the current state of things, it seems).

**Comment by saurabhnanda** [comment]
> I think these things belong in external libraries

Any recommendations for such libraries?

**Comment by saurabhnanda** [comment]
> Here we chose to have a one-to-many mapping (one PG type maps to several haskell types). This is probably also too (or not enough) restrictive for some. I would like a way to work around all the ambiguity opaleye's many-to-many mapping results in because this still affects us. Maybe it's possible, I haven't really thought about it.

Can you please elaborate this point? Are you referring to 1:1, 1:many, many:many mappings between tables/rows? I was referring to PGInt4 <=> Integer, PGText <=> Text. Aren't there sensible defaults possible for the data-type mappings?

**Comment by saurabhnanda** [comment]
Here's what I [mean by boilerplate](https://github.com/vacationlabs/haskell-webapps/blob/cd79a0f00f464f6f76e589912765ddb5daddbb88/ServantOpaleye/DB.hs). Surely there is a way to reduce this?

Also, is the purpose of defining a polymorphic record-type only to make the definition of concrete types easier? If yes, then what about the disadvantage of making sure the order of columns is always the same? It's a significant cognitive overhead.

**Comment by tomjaguarpaw** [comment]
> Also, is the purpose of defining a polymorphic record-type only to make the definition of concrete types easier?

The purpose of the polymorphic record type is largely to allow sharing of field accessors and encode relationships between types that are structurally very similar.

> If yes, then what about the disadvantage of making sure the order of columns is always the same? It's a significant cognitive overhead. 

What do you mean "order of colums is the same"?

**Comment by saurabhnanda** [comment]
> The purpose of the polymorphic record type is largely to allow sharing of field accessors and encode relationships between types that are structurally very similar

Overlooked this advantage, because I've moved to using lenses extensively. Also, with overloaded field accessors in GHC8, is this advantage also covered?

> What do you mean "order of colums is the same"?

```
data UserPoly a b c d e f g = User {}
type UserPGRead = UserPoly ...
```

It's not possible to write UserPGRead without referring to UserPoly. Anything that I write will compile, there is nothing else guiding me to write the correct code.

**Comment by tomjaguarpaw** [comment]
> It's not possible to write UserPGRead without referring to UserPoly. Anything that I write will compile, there is nothing else guiding me to write the correct code.

You can create `UserPoly`s of any field types but there are restrictions when it comes to using them!  You can't try to insert `UserPoly`s of the wrong type into the database, for example.

**Comment by tomjaguarpaw** [comment]
Perhaps you could give a concrete example of your concern.

**Comment by saurabhnanda** [comment]
Is the code given at https://github.com/tomjaguarpaw/haskell-opaleye/blob/56a15c6a7b89d517ddbef57720dfb207a4e387c9/Doc/Tutorial/TutorialManipulation.lhs#L130-L136 the only way to insert a record and return the newly created row's ID? Isn't it way too complicated for a simple operation?

Btw, is this [related piece of code in the Opaleye+Servant tutorial a bug](https://github.com/nomicflux/servant-opaleye-blog/issues/4)?

**Comment by tomjaguarpaw** [comment]
> Is the code given at https://github.com/tomjaguarpaw/haskell-opaleye/blob/56a15c6a7b89d517ddbef57720dfb207a4e387c9/Doc/Tutorial/TutorialManipulation.lhs#L130-L136 the only way to insert a record and return the newly created row's ID

No, it isn't the way to insert a record and return the newly created row's ID, let alone the *only* way.  The tutorial is somewhat misleading and should be improved.  The key part is at the bottom:

> This tutorial has only shown you how to generate the SQL string for
manipulation queries.  In practice you actually want to run them!  To
run them you should use `runInsertMany` instead of `arrangeInsertManySql`,
`runDelete` instead of `arrangeDeleteSql`, etc..

So you should use `runInsertManyReturning` which is slighly simpler.

**Comment by tomjaguarpaw** [comment]
If you need more help with this please reopen.
