### ISSUE TITLE
Does Opaleye handle DB transactions?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#206]
I couldn't find anything in the standard tutorials, source code search, or API docs. How do I wrap a bunch of SQL statements into a DB transaction with ability to rollback/commit?

The closest I could find is the [opaleye-trans library](https://hackage.haskell.org/package/opaleye-trans-0.3.2/docs/Opaleye-Trans.html#t:transaction), which seems to be using `withTransaction` provided by postgres-simple. Is that the recommend way?

**Comment by tomjaguarpaw** [comment]
Opaleye itself provides nothing to do with transactions.  You can start a transaction yourself on your connection using whatever method you choose, run Opaleye queries, and then terminate your transaction.  I've never used opaleye-trans, but if that works for you, go for it!

@bergmark @hesselink @WraithM may be able to provide input.

**Comment by saurabhnanda** [comment]
Btw, is this the best place to ask such queries? I seem to be on a roll wrt to primarily documentation clarifications.

**Comment by saurabhnanda** [comment]
> You can start a transaction yourself on your connection using whatever method you choose

What are the various options available?

**Comment by bergmark** [comment]
We have our own abstraction for transactions: https://github.com/silkapp/silk-opaleye/blob/master/src/Silk/Opaleye/Transaction.hs

**Comment by tomjaguarpaw** [comment]
> is this the best place to ask such queries?

Yes, you're welcome to ask here.  You ask good clarifying questions but it's hard to keep up with the pace, so please be patient :)



> > You can start a transaction yourself on your connection using whatever method you choose

> What are the various options available?

Issuing an explicit transaction using postgresql-simple is the most obvious one I can think of.

**Comment by hesselink** [comment]
To elaborate a little bit on @bergmark's remark: our abstraction is a monad `Q` which represents a transaction. You can sequence `Q` actions to compose them into a single transaction, and run them to actually perform the transaction. It will retry the transaction 3 times, committing if successful and aborting if not. The `Transaction` type class is the same thing but as a type class, so you can use it with monad stacks (like `MonadIO` instead of `IO`).

Underlying this there is just postgresql-simple's `withTransaction`, like @tomjaguarpaw suggested.

**Comment by WraithM** [comment]
Just to add some motivation for `opaleye-trans`: If you're familiar with `STM`, `opaleye-trans` basically has the same abstraction just using `withTransaction` under the hood. `withTransaction` can cause really confusing errors if you call `withTransaction` inside `withTransaction`. `opaleye-trans` is designed to make nesting transactions cause type-errors. If you have any questions about `opaleye-trans`, I'd be happy to answer them.

**Comment by hesselink** [comment]
@WraithM That looks very similar to what we have: your `Transaction` is our `Db`, and your `OpaleyeT` is similar to our `MonadPool` (specifically the `ReaderT` instance, which I think should have been newtyped, but oh well).

**Comment by WraithM** [comment]
@hesselink Yeah! They are very similar. We don't use `mtl` in our stuff, so `opaleye-trans` is `transformers`-style. Your retry logic is interesting. `opaleye-trans` doesn't do that at all. Do you run into issues with the overlapping instances?

There's also [opaleye-classy](https://hackage.haskell.org/package/opaleye-classy) for `mtl`-style Opaleye monad transformers, but I don't think `opaleye-classy` has any transaction abstraction.

@saurabhnanda With respect to  a place for asking questions, some people idle in #haskell-opaleye on Freenode, but most of those people also hang out in #chicagohaskell, which is much more active, too.

**Comment by saurabhnanda** [comment]
Are transactions not part of Opaleye because of time constraints or is it a conscious library design decision?

**Comment by hesselink** [comment]
@WraithM I haven't run into many issues with overlapping instances. You could probably set up some situation where it picks an unexpected instance, but in my experience that doesn't happen in practice. Is doesn't feel very principled though, which is why I prefer the newtype.

The retry logic is useful if you have to deal with with deadlocks, or occasionally if there's a random failure. We've had one or two cases where it's bitten us though, where we were trying to timeout a query and we ended up running it three times :-P

**Comment by tomjaguarpaw** [comment]
> Are transactions not part of Opaleye because of time constraints or is it a conscious library design decision?

A bit of both.

I don't think (though correct me if I'm wrong) that there is a single "best" way to handle transactions and any such functionality can be implemented in a third-party library without any need for access to the Opaleye internals.  In that sense it's a conscious design decision.

On the other hand I would be happy to implement some basic transaction functionality in Opaleye or integrate more closely with the two implementations mentioned above, if I had unlimited time.

**Comment by tomjaguarpaw** [comment]
If you need more help with this please reopen.
