### ISSUE TITLE
How can I make a certain field to be read only

### ISSUE THREAD

**Issue by sras** [tomjaguarpaw/haskell-opaleye#234]
How can I make the auto-incremented primary key field to be read only so that creates/updates won't be ever permitted to set the value directly and enforce it in type system.

Expanding a bit more on how I expect this to work; May be we can add a ReadOnly wrapper (like the Nullable wrapper that is already provided). So the the table definition of a table with a read only id filed can look something like this.
    
    type TenantTableW = TenantPoly
      (Column (ReadOnly PGInt4))
      (Maybe (Column PGTimestamptz)) -- createdAt
      (Column PGTimestamptz) -- updatedAt
      (Column PGText)
      (Column PGText)
      (Column PGText)
      (Column PGText)
      (Column PGText)
      (Maybe (Column PGText))
      (Maybe (Column (Nullable PGInt4)))
      (Column PGText)

    type TenantTableR = TenantPoly
      (Column PGInt4)  
      (Column PGTimestamptz) 
      (Column PGTimestamptz) 
      (Column PGText)
      (Column PGText)
      (Column PGText)
      (Column PGText)
      (Column PGText)
      (Column PGText)
      (Column (Nullable PGInt4))
      (Column PGText)

    tenantTable :: Table TenantTableW TenantTableR
    tenantTable = Table "tenants" (pTenant
       Tenant {
         _tenantpolyId = (readonly "id"),
         _tenantpolyCreatedat = (optional "created_at"),
         _tenantpolyUpdatedat = (required "updated_at"),
         _tenantpolyName = (required "name"),
         _tenantpolyFirstname = (required "first_name"),
         _tenantpolyLastname = (required "last_name"),
         _tenantpolyEmail = (required "email"),
         _tenantpolyPhone = (required "phone"),
         _tenantpolyStatus = (optional "status"),
         _tenantpolyOwnerid = (optional "owner_id"),
         _tenantpolyBackofficedomain = (required "backoffice_domain")
       }
     )

    data ReadOnly a = ReadOnly
    required :: String -> TableProperties (Column (ReadOnly a)) (Column a)

And may be, define a default instances for the pair (), Column (Readonly PGInt4) ,so that a read only field can only accept empty tuples as input.

**Comment by saurabhnanda** [comment]
Adding a little more context to this. Here's the motivation for what we're trying to achieve:

The base polymorphic type we have:

```
data TenantPoly key createdAt updatedAt name status ownerId backofficeDomain = Tenant {
  tenantKey :: key
  ,tenantCreatedAt :: createdAt
  ,tenantUpdatedAt :: updatedAt
  ,tenantName :: name
  ,tenantStatus :: status
  ,tenantOwnerId :: ownerId
  ,tenantBackofficeDomain :: backofficeDomain
  } deriving Show
```

The `NewTenant` type we have, which represents a new, uncreated tenant. Few fields have the type `()` because we want to be 100% sure that the UI is never able to pass-in any values for those fields.

```
type NewTenant = TenantPoly
  () -- key
  () -- createdAt
  () -- updatedAt
  Text -- name
  () -- status
  (Maybe UserId) -- ownerId
  Text -- backofficeDomain
```

Taking this type-safety further, we would like to define the following type for PG writes. 

* `id` should be unwritable because it will **always** be auto-assigned by the DB. And once assigned, it should not be possible to `UPDATE` it.
* `updatedAt` should **always** be required in any write operation (`INSERT` or `UPDATE`), because the app should be updating this field to the current timestamp [1]

```
type TenantPGWrite = TenantPoly
  () -- key
  (Maybe (Column PGTimestamptz)) -- createdAt
  (Column PGTimestamptz) -- updatedAt
  (Column PGText) -- name
  (Column PGText) -- status
  (Column (Nullable PGInt8)) -- ownerId
  (Column PGText) -- backofficeDomain
```

[1] We are trying to build two approaches here: (a) Managing the `createdAt` and `updatedAt` fields in Haskell, and (b) managing them in DB (using triggers). This question is in context of (a) -- getting Haskell to manage these fields.

**Comment by tomjaguarpaw** [comment]
Does this do what you want?

````haskell
import Opaleye
import Data.Profunctor

readOnly :: String -> TableProperties () (Column a)
readOnly = lmap (const Nothing) . optional
````

**Comment by sras** [comment]
Yes. This works. Thanks.

**Comment by tomjaguarpaw** [comment]
`readonly` doesn't do what I expected it to do, sorry.  It should probably be considered broken.

https://github.com/tomjaguarpaw/haskell-opaleye/issues/263#issuecomment-274266190
