### ISSUE TITLE
Explicitly cast literals?

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#253]
Because of issues like https://github.com/tomjaguarpaw/haskell-opaleye/issues/250#issuecomment-265146334 should we explicitly cast literals on creation?  It will make the generated SQL more verbose but more explicit and perhaps ultimately clearer.

**Comment by xldenis** [comment]
>  should we explicitly cast literals on creation? 

According to https://github.com/lpsmith/postgresql-simple/issues/199#issuecomment-265158844 it seems like only text values need to be cast. That would definitely help with the generated sql. The issue also only occurs in the return, for the inserted values psql can infer their types from the columns of the table. I had the same issue occur when manipulating constant ranges since it wasnt able to infer the numeric types without  a table schema to inform it.

**Comment by tomjaguarpaw** [comment]
Surely number types would need to be cast too so that Postgres can distinguish between int4, int8, numeric etc.?

**Comment by xldenis** [comment]
> Surely number types would need to be cast too so that Postgres can distinguish between int4, int8, numeric etc.?

Yea, sorry those need casts well. However, again this only applies in situations where postgres cannot leverage a table schema for inference. (ie: returning constant tuple after insert)

**Comment by tomjaguarpaw** [comment]
Agreed, though for simplicity I think we should do it for all literals.

**Comment by xldenis** [comment]
Should we consider using the `a :: b` syntax instead of `CAST` then for readability reasons?

**Comment by tomjaguarpaw** [comment]
I can't remember why I chose `CAST` but I think there are some cases where `::` doesn't work.

**Comment by tomjaguarpaw** [comment]
Perhaps it was that `CAST` is SQL standard, but I'm quite happy to keep `CAST` in any case.

**Comment by xldenis** [comment]
It doesnt matter much anyways.
