### ISSUE TITLE
Can we have Arrow Aggregator?

### ISSUE THREAD

**Issue by ocharles** [tomjaguarpaw/haskell-opaleye#282]
`Aggregator`s are `Profunctors`, but they are not `Category`s or `Arrow`s. Is that intentional?

**Comment by ocharles** [comment]
Now that I think about it, I guess it doesn't make sense. Morally, `Aggregator = [a] -> b`, which is not a category.

**Comment by ocharles** [comment]
Hmm, or maybe it does make sense. `NonEmpty a -> b` is a Cokleisli arrow, and those do form a category. Morally `Aggregator` is really acting over non-empty groups of rows (right?). Further more, the implementation is just a `PackMap`, which is just a traversal and again - those compose. I'm mostly wanting `Arrow` to get `proc` notation. Right now with `ApplicativeDo` we can at least use `do` notation, but `groupBy`, `sum`, etc, all have to be `lmap`ed which is a little messy.

**Comment by ocharles** [comment]
I think I see now that the problem is `id` would let you return a `Column` without aggregating *or* grouping by it. We really want `id = groupBy`. Hm.

**Comment by tomjaguarpaw** [comment]
> Aggregators are Profunctors, but they are not Categorys or Arrows. Is that intentional?

Yes, it's intentional.  I suspect that there is not a valid `Cagetory` instance.

> the problem is id would let you return a Column without aggregating or grouping by it

Correct

The "correct" solution would be to extend `Arrow` notation to `ProductProfunctor` notation.  It would be similar to the extension of `Monad` notation to `Applicative` notation.  `ProductProfunctor` notation would be the same as `Arrow` notation with the restriction that commands can only take arguments than only depend on stuff captured in the `proc`, not the output of other commands (and there would have to be a special case for `returnA` just like for `return`.  For example

````haskell
-- Works for any ProductProfunctor
proc (x, y, z) -> do
    a <- arrow1 -< f x
    b <- arrow2 -< g x z
    returnA -< h a b
````

````haskell
-- Only works for Arrows because arrow2's
-- argument depends on the output of arrow1
proc (x, y, z) -> do
    a <- arrow1 -< f x
    b <- arrow2 -< g a z
    returnA -< h a b
````

**Comment by ocharles** [comment]
Thanks for the discussion!
