### ISSUE TITLE
missing unField :: Field a -> PrimExpr

### ISSUE THREAD

**Issue by rsoeldner** [tomjaguarpaw/haskell-opaleye#455]
I"m missing the `unField :: Field a -> PrimExpr`, is this intended ?

**Comment by tomjaguarpaw** [comment]
I suppose I should add `Field` versions of all the internal `Column` functions, but because they are internal I haven't given it high priority.  I suggest you just use `unColumn` if you need this functionality (although be careful because it is undocumented, internal and subject to change without notice!).
