### ISSUE TITLE
Documentation request: newtype-wrappers using type families approach

### ISSUE THREAD

**Issue by russellmcc** [tomjaguarpaw/haskell-opaleye#483]
Hi!  Really enjoying opaleye so far.  Apologies for this vague question - please consider this more of a "support forum post" rather than a specific issue and feel free to close if it's too vague.

I'm trying to create a `newtype` wrapper for my IDs while using the `Opaleye.TypeFamilies` way of defining tables.  My issue is that I don't really understand many of the underlying mechanisms and am proceeding mostly through a "guess-and-check" approach.  It's a credit to the library that I can be as productive as I have been without fully understanding what's going on - thank you!  However, I could really use a reference to some documentation about either how some of these mechanisms work or an "official" approach to using newtype wrappers around ID fields.

here's what I've got so far:

```
data IDTag = DeckIDT | UserIDT

newtype IDP (t :: IDTag) n r f
  = ID
      { getID :: TableRecordField f Int SqlInt4 n r
      }

data UserP f
  = User
      { userID :: IDP 'UserIDT NN Opt f,
        userName :: TableRecordField f Text SqlText NN Req,
        userPasswordHash :: TableRecordField f Text SqlText N Req,
        userProfile :: TableRecordField f Value SqlJsonb NN Req
      }

data DeckP f
  = Deck
      { deckID :: IDP 'DeckIDT NN Opt f,
        deckName :: TableRecordField f Text SqlText NN Req,
        deckOwner :: IDP 'UserIDT N Req f,
        deckMetadata :: TableRecordField f Value SqlJsonb NN Req,
        deckPublic :: TableRecordField f Bool SqlBool NN Req
      }
```

Here I've omitted boilerplate for defining the `Default` instances and product profunctor "adaptors" - e.g., `pUser ::  PP.ProductProfunctor p => UserP (p :<$> a :<*> b) -> p (UserP a) (UserP b)`, and the table definitions.  The `TutorialBasicTypeFamilies.lhs` tutorial mentions that there's no way of auto-generating this boilerplate yet - is this still true?

Is this a solid approach for a newtype wrapper around IDs?  It's mostly working for me, but one slight annoyance is converting between the `Opt` `UserID` field in the `User` record and the `Req` field in the `Deck` record - to do this I've written helpers like

```
o2r :: IDP t NN Opt H -> IDP t NN Req H
o2r = ID . getID

r2o :: IDP t NN Req H -> IDP t NN Opt H
r2o = ID . getID
```

Then I have to sprinkle these helpers in queries when converting from one form of the ID to the other - is there a way to eliminate these helpers?

**Comment by tomjaguarpaw** [comment]
> tutorial mentions that there's no way of auto-generating this boilerplate yet - is this still true?

Unfortunately so. I don't think there's any reason that this couldn't be done reasonably straightforwardly. It just requires someone to do the work.

> Is this a solid approach for a newtype wrapper around IDs?

It's certainly a neat idea! I don't see anything wrong with it. I guess the proof of the pudding will be whether it works ergonomically for you. There is no way that you can "break" Opaleye by using interesting new type definition schemes (or at least if there is then please file a bug on Opaleye!) so the only thing to consider is whether you find this style convenient.

That said, one reason the type families stuff was implemented as a way of getting around various awkwardness around inference. With the new `Inferrable` API inference is much less of a problem and the type families stuff is probably less necessary.

> Then I have to sprinkle these helpers in queries when converting from one form of the ID to the other - is there a way to eliminate these helpers?

Hmm, I think not because `IDP t NN Opt H` and `IDP t NN Req H` genuinely are different types. I'm afraid I'm not really familiar enough with "type level" Haskell to see an obvious improvement here.

**Comment by russellmcc** [comment]
Thanks for the response!  I really appreciate it.

**Comment by tomjaguarpaw** [comment]
You're welcome Russell. Feel free to ask any time.
