### ISSUE TITLE
runSelectI fails to deduce FromField SqlTimestamptz UTCTime, but runSelect works fine.

### ISSUE THREAD

**Issue by njaremko** [tomjaguarpaw/haskell-opaleye#495]
Hello everyone,

I'd like to start by thanking you for Opaleye, it's been awesome (mostly, but we'll get into that :stuck_out_tongue:) 

I've run into this issue where `runSelectI` is failing to compile due to an inability to deduce a typeclass instance. However, the same select runs fine if I use `runSelect` instead. `runSelectI` supposedly (according to the docs) has better type inference, so I figured I'm either being dumb, or this is a bug.

I'd appreciate any help you can offer :smile: 

```
Could not deduce (Default
  (Inferrable FromField)
  SqlTimestamptz
  time-1.9.3:Data.Time.Clock.Internal.UTCTime.UTCTime)
```

This version works
```haskell
fetchByUserId ::
  ( Default FromFields ApiCredentialField a,
    Default ToFields haskells User.UserIdField
  ) =>
  Connection ->
  haskells ->
  IO [a]
fetchByUserId conn userId = do
  runSelect conn selectByUserId
  where
    selectByUserId = do
      p@ApiCredential {user_id} <- selectTable apiCredentialTable
      viaLateral restrict $ user_id .=== toFields userId
      return p
```

But this version doesn't

```haskell
fetchByUserId ::
  ( Default
      (Inferrable FromFields)
      ApiCredentialField
      haskells1,
    Default ToFields haskells2 User.UserIdField
  ) =>
  Connection ->
  haskells2 ->
  IO [haskells1]
fetchByUserId conn userId = do
  runSelectI conn selectByUserId
  where
    selectByUserId = do
      p@ApiCredential {user_id} <- selectTable apiCredentialTable
      viaLateral restrict $ user_id .=== toFields userId
      return p
```

The type looks like this:

```haskell
data ApiCredential' a b c d e = ApiCredential
  { id :: a,
    user_id :: b,
    test_secret_key :: c,
    live_secret_key :: d,
    created_at :: e
  }
  deriving stock (Generic)

type ApiCredential =
  ApiCredential'
    ApiCredentialId
    User.UserId
    Text
    Text
    UTCTime

type ApiCredentialField =
  ApiCredential'
    ApiCredentialIdField
    User.UserIdField
    (Field SqlText)
    (Field SqlText)
    (Field SqlTimestamptz)

type ApiCredentialFieldWrite =
  ApiCredential'
    ApiCredentialIdFieldWrite
    User.UserIdField
    (Maybe (Field SqlText))
    (Maybe (Field SqlText))
    (Maybe (Field SqlTimestamptz))

apiCredentialTable :: Table ApiCredentialFieldWrite ApiCredentialField
apiCredentialTable =
  table
    "api_credentials"
    ( pApiCredential
        ApiCredential
          { id = pApiCredentialId (ApiCredentialId (optionalTableField "id")),
            user_id = User.idField "user_id",
            test_secret_key = optionalTableField "test_secret_key",
            live_secret_key = optionalTableField "live_secret_key",
            created_at = optionalTableField "created_at"
          }
    )
```

**Comment by tomjaguarpaw** [comment]
Hi @njaremko! I'm glad Opaleye has been working well with you. Let's try to resolve your problem. The ultimate cause is that [Postgres has two timestamp types](https://www.postgresql.org/docs/9.1/datatype-datetime.html) and [the `time` library has three](https://hackage.haskell.org/package/time-1.11.1.1/docs/Data-Time.html) and it's hard to make an exact correspondence. Specifically

Postgres:

* `timestamp`
* `timestamptz`

`time`:

* `LocalTime`
* `ZonedTime`
* `UTCTime`

The question is how to pair these off inferrably.

### `Inferrable ToField`

* `LocalTime` should map to `timestamp`. It can't map to a `timestamptz` because it doesn't come with any notion of time zone.
* `ZonedTime` should map to `timestamptz` because it does come with a time zone.
* `UTCTime` is less clear. If it were mapped to `timestamp` then we'd have to discard the `UTC` time zone and it would just be implicitly stored in UTC rather than explicitly. On the other it can be mapped it to a `timestamptz` with an explicit `UTC` time zone. The latter seems like the better approach and it's what [`postgresql-simple` does](https://hackage.haskell.org/package/postgresql-simple-0.6.4/docs/src/Database.PostgreSQL.Simple.Time.Internal.Printer.html#utcTime) too. This is what Opaleye chooses too, though in retrospect it may have been better not to include this instance but instead to require users to run [`zonedTimeToUTC`](https://hackage.haskell.org/package/time-1.11.1.1/docs/Data-Time-LocalTime.html#v:zonedTimeToUTC) for explicitness. I'm not sure.

### `Inferrable FromField`

* `timestamp` should map to `LocalTime` otherwise we would have to make an implicit choice about the time zone that it is supposed to be stored with reference to.
* The mapping for `timestamptz` is not currently implemented, as you discovered. It should *probably* map to `ZonedTime` because otherwise the time zone that it explicitly contains will be discarded. On the other hand users who, like you, want a `UTCTime` will have to run [`zonedTimeToUTC`](https://hackage.haskell.org/package/time-1.11.1.1/docs/Data-Time-LocalTime.html#v:zonedTimeToUTC) to get one.

### Full mapping

Type  | `timestamp` | `timestamptz`
-- | ------------ | -------------
`LocalTime` | `FromField`/`ToField` | 
`ZonedTime` |  | `FromField`*/`ToField`
`UTCTime` | | `ToField`

(*) Proposed but doesn't yet exist.

@njaremko and others: what do you think about this? I'd prefer to get this right first time because deprecating instances is difficult

**Comment by njaremko** [comment]
If there's no instance of `FromField`, then why does `runSelect` work? Is the issue that `(Inferrable FromField)` requires that there be only one instance of the typeclass for `SqlTimestamptz`, but two exist? If we can only have one instance, I'd agree that it should be ZonedTime, since that is the most accurate mapping to Postgres' timestamptz.

**Comment by tomjaguarpaw** [comment]
> If there's no instance of FromField, then why does runSelect work?

I updated the header to make it clear that the table is specifically for `Inferrable` instances.

> Is the issue that (Inferrable FromField) requires that there be only one instance of the typeclass for SqlTimestamptz, but two exist?

The issue is that two instances of `FromField` exist but only one of `Inferrable FromField` can exist and I haven't chosen one yet.

> If we can only have one instance, I'd agree that it should be ZonedTime, since that is the most accurate mapping to Postgres' timestamptz.

OK great, I'll go ahead with that.

**Comment by tomjaguarpaw** [comment]
OK, I have added this on branch `inferrable-fromfield-timestamptz`.

@njaremko I'd appreciate it if you'd test this and confirm that it fixes your problem.

**Comment by njaremko** [comment]
Yes, after replacing `UTCTime` with `ZonedTime`, `runSelectI` works as expected

**Comment by tomjaguarpaw** [comment]
Great! I have pushed that to `rc`. It will hit `master` and a Hackage release in due course. Please let me know if you if and when you need a Hackage release.

**Comment by njaremko** [comment]
Thanks for your help on this Tom 👍

**Comment by lfborjas** [comment]
Hi @tomjaguarpaw! Sorry to comment on a closed ticket, but I recently ran into this as well, and after initially working with `ZonedTime` as the default inferrable instance when querying my database, I believe that in the interest of the principle of least surprise, `UTCTime` should be the default inferrable instance. 

For starters: **postgres doesn't actually store the _input_ timezone**, as [per the docs](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-TIMEZONES):

> All timezone-aware dates and times are stored internally in UTC. They are converted to local time in the zone specified by the TimeZone configuration parameter before being displayed to the client.

Since PG stores `timestamp with time zone` as the input instant in UTC, I think`UTCTime` when querying would be the least surprising choice: `ZonedTime` may lead one to believe that the timezone _one saved a datum with_ is coming back, but it won't: it will come back as the right instant in time, but with whatever timezone the Postgres server is configured with, which can be confusing if one _knows_ a different timezone should be coming back -- when _writing_, I fully agree that it's safe and reasonable that a `ZonedTime` value can be given to PG from opaleye, and it _will_ of course still store the right instant in time.

(See also [this stackoverflow](https://stackoverflow.com/a/9576170) thread, or [this other one](https://stackoverflow.com/questions/51132868/incorrect-date-fetched-from-postgres))

My use case that illustrated this was: my application receives user input, and is aware of their timezone -- I'm receiving local times from end users, plus their geographic location, and deriving the timezone; in Haskell, I end up with a `ZonedTime` value in the end user's local timezone which I persist to a `timestamp with time zone`. I was expecting this to "round trip," but it didn't: PG returned the right instant in time, but the timezone in the `ZonedTime` wasn't the end user's time zone, but instead the database server timezone! After some investigation, I realized that this is on fault of our app code or Opaleye itself, it's simply the wrong expectation: PG will definitely give us back the right instant, but it never promised to remember the input timezone! Here's some SQL to illustrate (examples from two servers I currently have access to, one configured to my local TZ, which is `EDT`, and another in `UTC`:)

```sql
dev=# show timezone;
     TimeZone     
------------------
 America/New_York
(1 row)

 dev=# select '1989-01-06T23:30:00-0600'::timestamptz;
      timestamptz       
------------------------
 1989-01-07 00:30:00-05
(1 row)
```

and the other server:

```sql
prod=> show timezone;
 TimeZone 
----------
 Etc/UTC
(1 row)

prod=> select '1989-01-06T23:30:00-0600'::timestamptz;
      timestamptz       
------------------------
 1989-01-07 05:30:00+00
(1 row)
```

For _my_ particular use case, since I _need_ to be able to display the timestamp back to the end user in the local time of their calculated timezone, I'm storing the timezone in a separate column so I can do stuff like:

```sql
# select moment as "Timestamp", moment at time zone timezone_name as "LocalTime", timezone_name from my_table where id = 2;
       Timestamp        |      LocalTime      |    timezone_name    
------------------------+---------------------+---------------------
 1989-01-07 00:30:00-05 | 1989-01-06 23:30:00 | America/Tegucigalpa
(1 row)
```

In Haskell, the first of those columns, inferred as `UTCTime`, reflects the right moment in time, which I use for internal calculations (if it was a `ZonedTime`, I would have to convert to UTC, which isn't a big deal since I know the temporal value is correct, but a casual maintainer would be bewildered to see the server timezone in there;) and I use the `timestamptzAtTimeZone` operator in opaleye to get a `LocalTime` back, too, for display purposes -- no misleading `ZonedTime` values that promise, but can't deliver :D (I do have some code that can take the `timezone_name` value and actually produce a `TimeZone` haskell value  that I can pair that `LocalTime` with, if I wanted a `ZonedTime` that's truthful to the input, but that's even further into my own use case hehe.)

**Comment by njaremko** [comment]
If you've configured postgres to return timestamps in the EST timezone, and the response to your query consequently has EST zoned timestamps, then it still seems to me like we should default to parsing as a zoned timestamp? 

You're expectation that the time zones should round trip was incorrect, but I don't think it's fair to blame that on the type being used. If postgres is providing a zoned timestamp (postgres persisting it in UTC under the hood seems irrelevant), we should probably be treating it as such, instead of implicitly converting it to UTC.

**Comment by lfborjas** [comment]
That's a good point! To clarify: I didn't _explicitly_ configure pg to use EST, it just so happened to install that way in this workstation where I'm trying out opaleye -- my company has a more strict policy of always using UTC in our database servers, to not befuddle any direct SQL querying/reporting with unexpected display timezones for our distributed team (fwiw, the bigger product we build is written in Java, which ingests `java.time.Instant` values and is not concerned with local time zones.)

My point was more about the fact that it seems unnecessary to me to ingest a zoned time from postgres that carries the server timezone: as an application developer, I either expect timestamps in UTC that I can then convert to any local timezone or just treat as instants in time, or if there's a time zone coming back, one that is intentional/applicable to the business logic i.e. if I put a `ZonedTime` in the DB, and I get a  `ZonedTime` back later, it would be a bit surprising if they carried a different timezone, and it seems extraneous to expect a casual maintainer of such a codebase to know how pg is dealing with things internally -- it seems _less_ surprising to say "hey, here's a UTC time, the server stores it as a universal instant and forgets any 'input' timezone, if you wanted me to remember a specific time zone, you need to store that explicitly" vs. "here's a ZonedTime, it's the right moment in time, but I hope you weren't expecting it to remember the timezone you put in there originally, this timezone is the server's!" -- it seems like a detail of the database server is leaking in a manner that seems to me unintentional.

As I said, as it is, it's easy to work with, and nothing _wrong_ is happening (no information is truly being lost,) so now that I know what's up, it's one line of code to conver that ZonedTime to UTCTime for my calculations/conversions; but thinking of a future maintainer, a `ZonedTime` creates a cognitive friction/expectation that a more barebones `UTCTime` doesn't.

**Comment by tomjaguarpaw** [comment]
@lfborjas, no need to apologise. Thanks for flagging this! Yikes! I completely misunderstood what `timestamptz` is.

Luckily there has been no Hackage release made with this code so we are at liberty, at least in principle, to break this interface. However I would be reluctant to do so unless absolutely necessary, especially since @njaremko is already using this interface.

However, what you say is compelling. Have a look at the following SQL.

```sql
SELECT (id, ts)
FROM  (
   VALUES
      (1, timestamp   '2012-03-05 17:00:00' AT TIME ZONE 'EST')
    , (2, timestamptz '2012-03-05 17:00:00' AT TIME ZONE 'EST')
      ) t(id, ts);
```

```
row
--
(1,"2012-03-05 22:00:00+00")
(2,"2012-03-05 12:00:00+00")
```

`timestamp` behaves like `Data.Time.LocalTime` and `timestamptz` behaves like `Data.Time.UTCTime`. `AT TIME ZONE` behaves like `localTimeToUTC` or `utcToLocalTime` depending on its argument type. The timezone doesn't exist at all in Postgres which makes me think that Opaleye shouldn't really be doing anything with `ZonedTime` at all.

```
> import Data.Time
> let parse = parseTimeM True defaultTimeLocale "%Y-%-m-%-d %H:%M:%S"
> let est = read "EST" :: TimeZone

> localTimeToUTC est <$> parse "2012-03-05 17:00:00"
2012-03-05 22:00:00 UTC
> utcToLocalTime est <$> parse "2012-03-05 17:00:00"
2012-03-05 12:00:00
```

It's not possible to remove the `ZonedTime` instance without a major version bump. Nonetheless I am inclined to do that for version 0.8. Perhaps in its place it would be helpful to have a `OpaleyeZonedTime` type which is a pair of an `SqlTimestamptz` and an `SqlText` representing a time zone. I would be interested in people's thoughts on this.

It *is* possible to change the `Inferrable` `ZonedTime` instances, since they have not been pushed to Hackage. @njaremko what do you think about this? Do you even agree with my reasoning above? If you do agree would it break you too badly to see this change?

**Comment by njaremko** [comment]
Don't hold back breaking changes on my account 😛 

I can definitely understand the argument that what postgres is giving us is an instant in time, possibly in a random timezone provided by the server, so normalizing to UTC makes sense. My only concern would be that we're then forcing implicit timezone conversion for all results returned by the DB (this conversion may actually be trivial, but I haven't benchmarked it). Unless you're planning on having all queries with timestamptz add `AT TIME ZONE 'UTC'` under the covers. If that's the case, then it sounds fine to me.

**Comment by lfborjas** [comment]
@tomjaguarpaw: oh dang, interesting finding about `timestamp`; I guess Postgres really generally defaults to its local time zone for temporal types, which is why they spend some sentences warning users about that in the manual! Also explains [this comment I saw in beam](https://github.com/haskell-beam/beam/blob/596981a1ea6765b9f311d48a2ec4d8460ebc4b7e/beam-postgres/Database/Beam/Postgres/Types.hs#L130-L143) when poking around -- which further leads me to think that maybe it's okay to lose some tz information in the "common case" if it may be misleading, vs. carry it back to the application.

That being said, I personally, as a user, would be totally okay with the `ZonedTime` `FromField` instance remaining: if there's a big ol' comment in the source, I can definitely see someone choosing to get that back explicitly if they _do_ want the server's time zone to leak through, and then do any conversions themselves. My only concern is merely about the `Inferrable` instance since that's the one in the "magic, don't worry about it" part of the interface: I'm partial to always going for the least surprising default for the less power-user-oriented features :D

Re. a richer type for those of us interested in persisting times _with_ time zones in a non-forgetful manner: that would be very cool, though I think there would still be some application-level code that maybe doesn't belong in Opaleye to actually do something (e.g. produce a `ZonedTime`, or convert to a `LocalTime`) with that textual timezone (maybe using the [`tz`](https://hackage.haskell.org/package/tz) package?)

As for @njaremko 's point about timezone conversions: that's fair, I'm not familiar with the current implementation so it may indeed be that there's some conversion overhead in the Haskell side if the server isn't using UTC; I also suspect that it's probably trivial though, or at least, there's always _some_ parsing overhead happening. As I said before, ideally Haskell would have an `Instant` type that doesn't commit to _any_ time zone!

Also, for our collective edification, [an article from the author of "the art of postgresql"]() going over all of this, and on a more Haskell-oriented note, the [postgres-simple writeup](https://hackage.haskell.org/package/postgresql-simple-0.6.4/docs/Database-PostgreSQL-Simple-Time.html) on this (which is a _very_ fascinating read!) advocates for both types as reasonable representations of `timestamptz`, but gives a tiny edge to `UTCTime` in the case of timestamps in the distant past:

> Both of these timestamps can be parsed as a UTCTime type, however ZonedTime will fail on the former timestamp. Because ZonedTime assumes that offsets are an integer number of minutes, there isn't an particularly good solution here.

**Comment by tomjaguarpaw** [comment]
@njaremko If [the postgresql-simple `UTCTime` parser](https://hackage.haskell.org/package/postgresql-simple-0.6.4/docs/src/Database.PostgreSQL.Simple.Time.Internal.Parser.html#utcTime) turns out to be too slow we can arrange for Opaleye to always return `timestamptz`s from the database in UTC (I think!) and parse them without having to do any conversion.

@lfborjas Yes, I see your point about keeping the `FromField` `ZonedTime` instance. I agree that, by contrast, the `Inferrable FromField` should always do the least surprising thing.

Thanks for the links to the postgresql-simple doc. It contains this revealing sentence, confirming what I just hypothesised!

>  One can convert between timestamptz and timestamp using the AT TIME ZONE operator, whose semantics also demonstrates that timestamptz is UTCTime whereas timestamp is LocalTime.

### Computations that depend on the timezone

However, this is grim:

>The correctness of server-side computations can depend on the timezone setting. Examples include adding an interval to a timestamptz ... or applying the DATE function to a timestamptz.

#### Adding an interval to a timestamptz

`Europe/Paris` changed from `CET` to `CEST` on `2021-03-28`:

```sql
SET timezone to 'Europe/Paris';
SELECT timestamptz '2021-03-28 00:00:01Z' + interval '1 day';
```

```
2021-03-28T23:00:01.000Z
```

`America/New_York` didn't:

```sql
SET timezone to 'America/New_York';
SELECT timestamptz '2021-03-28 00:00:01Z' + interval '1 day';
```

```
2021-03-29T00:00:01.000Z
```

So the result of `<timestamptz> + interval '1 day'` depends on the server timezone. That doesn't sound like the behaviour of a `UTCTime`! It's more like the behaviour of a `LocalTime` with implicit timezone.

On the other hand, `<timestamp> + interval '1 day'` does not depend on server timezone, which is behaviour more like `UTCTime`. (I don't think it's even sensible to be able to add an interval to a `LocalTime` actually. Time [does support this](https://hackage.haskell.org/package/time-1.11.1.2/docs/src/Data.Time.LocalTime.Internal.LocalTime.html#addLocalTime) but only by assuming the `LocalTime` is in UTC.)

So `timestamptz` and `timestamp` do not *always* behave like `UTCTime` and `LocalTime` respectively.

(And adding `interval '24 hours'` gives the same result in every case.)

#### Applying DATE to a timestamptz

Applying the DATE function takes the UTC time and finds the local date of that time in the server timezone!

```sql
SET timezone to 'Europe/Paris';
SELECT date (timestamptz '2021-03-28 00:00:01 Z');
```

```
2021-03-28T00:00:00.000Z
```

```sql
SET timezone to 'America/New_York';
SELECT date (timestamptz '2021-03-28 00:00:01 Z');
```

```
2021-03-27T00:00:00.000Z
```

On the other hand, converting to a `timestamp` using `IN TIME ZONE 'UTC'` gives the date of the original `UTCTime`.

```sql
SET timezone to 'Europe/Paris';
SELECT date (timestamptz '2021-03-28 00:00:01 Z' AT TIME ZONE 'UTC');
```

```
2021-03-28T00:00:00.000Z
```

```sql
SET timezone to 'America/New_York';
SELECT date (timestamptz '2021-03-28 00:00:01 Z' AT TIME ZONE 'UTC');
```

```
2021-03-28T00:00:00.000Z
```

Again, `timestamptz` and `timestamp` do not behave as `UTCTime` and `LocalTime`.

### What should Opaleye do?

I suppose we have a couple of orthogonal dimensions

1. Implement Postgres time and date functionality directly (possibly warning users about these weirdnesses), or not.

2. Implement somewhat more sane wrappers around Postgres time and date functionality that do The Right Thing(TM).

We already partially do 1, and I think it is correct to do so to enable people to work with legacy databases and queries.

I think it would also be worthwhile doing 2 but is a fair amount of work to design.

### Infelecities in `time`

Reading this document also makes me aware of some infelicities in `time`. It sounds like `ZonedTime` should really be called `LocalTimeWithOffset` and `UTCTime` should (probably) be called `Instant`: the fact that it's stored internally in UTC is an implementation detail..

**Comment by tomjaguarpaw** [comment]
OK, I think I've understood the underlying model that explains all this:

1. `timestamp` is like a reading on a standard clock that has no knowledge of time zones or any features more complicated than displaying a time and date and being able to be wound forward and backward. (Perhaps this is what `LocalTime` is supposed to be. I always interpreted `LocalTime` as "a time in a particular locale but I won't tell you which" but perhaps I was wrong.)
2. `timestamptz` is an *instant* but everything that is done to it is implicitly done in the current connection's time zone.

I think this explains everything that we have seen.

#### `timestamptz`

When a `timestamptz` is parsed it is interpreted as though it were a local time in the time zone of the connection (unless it has an explicit time zone). It is converted to UTC for storage because it is an *instant* not a zoned local time. Two `instant`s that are equal ought to compare equal even if they were inserted by two clients which each set the connection to their own time zone. If I set my connection timezone to `Europe/London` and insert `2000-01-01 00:00:00` and you set your connection to `Europe/Paris` and insert `2000-01-01 01:00:00` then the two `timestamptz`'s will compare equal, because they are the same *instant*.

However, if one does a time zone dependent operation to a `timestamptz`, like add `1 day` or take its `DATE`, that operation will be done implicitly in the connection's time zone. When you inspect it `AT TIME ZONE` the connection's time zone is irrelevant so the result is indistinguishable from what would happen if the implementation detail (that it's stored in `UTC`) were actually its specification. *In that use case* it behaves like a UTC time, but in general it does *not* behave like a UTC time, because it is not one.

#### `timestamp`

`timestamp` is simpler. We can add intervals to `timestamp`s because that just corresponds to winding on the clock a certain length of time. The connection time zone is completely irrelevant for anything related to a `timestamp` (that doesn't also involve a `timestamptz`).

**Comment by lfborjas** [comment]
Thanks for this writeup @tomjaguarpaw, I learned a ton! It makes a lot of sense to me that a `timestamp without time zone` is equivalent to "wall time," unconcerned with _actual_ instants in time, able to operate in a "zoneless" abstraction, and that Haskell's `LocalTime` embodies the same concept; whereas `timestamp with time zone` _is_ an instant in physical time and as such, zone-dependent operations on it will "force/collapse" it to become aware of its current time zone context. Guess that's why [some shops](https://www.cockroachlabs.com/blog/time-data-types-postgresql/), mine included, just recommend using UTC in the server -- though if that had been the case in my workstation, I wouldn't have learned any of this!

I believe your discoveries align with [this thread I found just now](https://dba.stackexchange.com/a/158003) -- which links to a [handy table for how Java maps its types to Postgres's](https://stackoverflow.com/a/41111089) 

Very Tangential Aside: interesting that in Java land, there's an `OffsetDateTime` that seems to _actually_ be the one that maps to [Haskell's ZonedTime](https://hackage.haskell.org/package/time-1.9.3/docs/Data-Time.html), because `TimeZone` in Haskell is just an offset, not the actual geopolitical time zone, which is [its whole fascinating function of space and time, which Haskell has a package for, too](https://hackage.haskell.org/package/timezone-series-0.1.9/docs/Data-Time-LocalTime-TimeZone-Series.html) in which the offset varies in ways beyond the simple summer time we use in some jurisdictions (e.g. in my birth time zone, we don't _always_ have DST, so the offset has changed only [a handful of times in the past century](https://timezonedb.com/time-zones/America/Tegucigalpa))
