### ISSUE TITLE
Streaming interface for queries?

### ISSUE THREAD

**Issue by hvr** [tomjaguarpaw/haskell-opaleye#68]
I've already asked this for the `groundhog` library (see https://github.com/lykahb/groundhog/issues/41), and now I'm wondering whether `opaleye` has support or plans to support a streaming-like interface for querying many tuples from a database in constant-space.

**Comment by tomjaguarpaw** [comment]
This is a very good idea.  [`postgresql-simple` already supports this](http://hackage.haskell.org/package/postgresql-simple-0.4.10.0/docs/Database-PostgreSQL-Simple.html#g:17) so it should be easy to add to Opaleye.

I have a feeling someone has already worked on such a patch, but a quick search didn't turn up anything.

We would need `foldWith_` which takes a `RowParser` rather than a `FromRow` constraint, but I'm sure Leon would be happy to merge that upstream.

**Comment by tstat** [comment]
I submitted a PR that was accepted on this in May https://github.com/lpsmith/postgresql-simple/pull/147 and have opaleye functions for working with this locally, but have not made any PRs to opaleye yet as Leon has not published to hackage since Feburary.

**Comment by tomjaguarpaw** [comment]
Thanks Travis!  Can you PR your patch anyway with a note saying we are waiting for an upstream Hackage release?  It would be good if people can see it's in the queue.

**Comment by tstat** [comment]
Sure thing, I'll go ahead and submit it when I get a free moment.

**Comment by tomjaguarpaw** [comment]
The PR is here https://github.com/tomjaguarpaw/haskell-opaleye/pull/69

**Comment by tomjaguarpaw** [comment]
I'm happy to merge #69 and close #68 as soon as I'm convinced it's OK to force everyone to upgrade to the lastest postgresql-simple.  Feel free to convince me!

**Comment by LukeHoersten** [comment]
Just bump the major version number. Back ported bug fixes can still be released under the previous major version.

**Comment by tomjaguarpaw** [comment]
This has been merged in HEAD for some time.  Anyone who especially wants a Hackage release (and this applies in general) please open another issue.
